apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-probe
spec:
  containers:
    - image:  nginx
      name:  nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /test
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 1
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3