apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    nama: nginx
    service: web-server
  namespace: kubernet-training
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80